<form class="form-horizontal" action="" method="post" name="adicionar">
	<div class="tabbable">
		<!-- Declaracao das Tabs -->
   		<ul class="nav nav-tabs">
			<li class="active"><a href="#tab1" data-toggle="tab">Dados Inicias da Ata</a></li>
   			<li><a href="#tab2" data-toggle="tab">Pontos de Pauta</a></li>
   			<li><a href="#tab3" data-toggle="tab">Revis&atilde;o</a></li>
   			<li><a href="#tab4" data-toggle="tab">Submiss&atilde;o</a></li>
   		</ul>
   		<!-- Area de conteudo das Tabs -->
   		<div class="tab-content">
		    <!-- Conteudo tab1 -->
		    <div class="tab-pane active" id="tab1">
		    	<div class="control-group">
					<label class="control-label" for="assunto">Assunto</label>
					<div class="controls">
						<input type="text" name="assunto" placeholder="Assunto">
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="data">Data</label>
					<div class="controls">
						<input type="text" name="data" placeholder="Data">
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="presente">Pessoas Presentes</label>
					<div id="usuarios" class="controls">
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="pontos">Pontos de Pauta</label>
					<div id="pontos" class="controls">
						<input type="text" name="pontos" id="pontos" class="campo">
						<i id="adicionar" title="Adicionar Ponto de Pauta" class="icon-plus"></i>
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="descricaco">Descri&ccedil;&atilde;o</label>
					<div class="controls">
						<textarea name="descricao"></textarea>
					</div>
				</div>
		    </div>
		    <!-- Conteudo tab2 -->
		    <div class="tab-pane" id="tab2" name="tab2">
		    	<div id="ajax-pontos" class="control-group">

				</div>
		    </div>
		    <!-- Conteudo tab3 -->
		    <div class="tab-pane" id="tab3" name="tab3">
		    </div>
		    <!-- Conteudo tab4 -->
		    <div class="tab-pane" id="tab4" name="tab4">
			</div>
		</div>
	</div>
</form>
<!-- Botoes Proximo e voltar -->
<div class="control-group">
	<div id="botoes" class="controls">
		<button class="btn" id="prevtab" type="button">Anterior</button>
		<button class="btn" id="nexttab" type="button">Pr&oacute;ximo</button>
		<input type="button" class="btn btn-danger" value="Cancelar">
	</div>
</div>
<!-- js para fazer funcionar as perfumarias -->
<script src="<?php echo $this->baseUrl()?>/public/js/bootstrap-tab.js"></script>
<script src="<?php echo $this->baseUrl()?>/public/js/abas.js"></script>
<script src="<?php echo $this->baseUrl()?>/public/js/adicionarPontos.js"></script>
<script src="<?php echo $this->baseUrl()?>/public/js/ajaxUsuarios.js"></script>