<div>
	<h3><?php echo $this->ata['assunto']; ?></h3>
</div>
<div>
	<p><b>Descricao:</b> <?php echo $this->ata['descricao']; ?></p>
</div>
<div>
	<p><b>Data:</b> <?php echo $this->ata['data']; ?></p>
</div>
<div>
	<p>
		<b>Pautas: </b><br/>
		<?php $contador = count($this->ata['pautas']) - 1;?>
		<?php for($i = 0; $i <= $contador; $i++): ?>
			<b><?php echo $this->ata['pautas'][$i]; ?></b><br/>
			<?php echo $this->ata['descricaoPontos'][$i]; ?><br/>
		<?php endfor; ?>
	</p>	
</div>
<div>
	<p>
		<b>Presentes: </b>
		<ul>
		<?php foreach($this->ata['presentes'] as $row => $linhas):?>
			<?php  foreach($linhas as $linha): ?>
				<li><?php echo $linha; ?></li>
			<?php endforeach;?>
		<?php endforeach; ?>
		</ul>
	</p>	
</div>
<div>
	<p><b>Status:</b> <?php echo ($this->ata['status'] == 0) ? "Salvo" : "Homologado"; ?></p>
</div>
<div>
	<a class="btn btn-primary" name="homologar" id="homologar-<?php echo $this->ata['_id']; ?>" href="<?php echo $this->baseUrl(); ?>/atas/index/update/id/<?php echo $this->ata['_id']; ?>">Homologar</a>
        <input type="hidden" class="status" alt="#homologar-<?php echo $this->ata['_id']; ?>" value="<?php echo $this->ata['status']; ?>">
	<input type="button" id="voltar" class="btn btn-danger" value="Voltar"><br/><br/>
	
</div>
<script src="<?php echo $this->baseUrl(); ?>/public/js/botaoVoltar.js"></script>
<script>
$(".status" ).each(function (i) {
if($(this).val()==1) {
ref = $(this).attr("alt");
$(ref).hide();
}
});
</script>
