<form action="<?php echo $this->baseUrl().'/index.php/usuarios/index/add';?>" method="post" class="form-horizontal">
	<fieldset><legend>Cadastro de Usuario</legend></fieldset>
	<div class="control-group">
		<label class="control-label" for="nome">Nome:</label>
		<div class="controls">
			<input type="text" id="nome" name="nome" placeholder="Nome">
		</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="email">Email</label>
		<div class="controls">
			<input type="email" name="email" id="email" placeholder="Email">
		</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="username">Username</label>
		<div class="controls">
			<input type="text" name="username" id="username" placeholder="Username">
		</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="password">Password</label>
		<div class="controls">
			<input type="password" name="password" id="password" placeholder="Password">
		</div>
	</div>
	<div class="control-group">
                <label class="control-label" for="re-password">Repita sua Password</label>
                <div class="controls">
                        <input type="password" name="re-password" id="re-password" placeholder="Repita sua Password">
                </div>
        </div>
	<div class="control-group">
		<div class="controls">
			<input type="submit" class="btn btn-success" value="Salvar">
			<input type="button" id="voltar" class="btn btn-danger" value="Voltar">
		</div>
	</div>
</form>
<script src="<?php echo $this->baseUrl(); ?>/public/js/botaoVoltar.js"></script>