<h2>Usu&aacute;rios cadastrados</h2>
<a class="btn btn-success" href="<?php echo $this->baseUrl();?>/index.php/usuarios/index/add"><i class="icon-user"></i> Adicionar Usuario</a>
<table class="table talbe-stripped table-hover">
	<thead>
		<tr>
			<th>Nome</th>
			<th>Email</th>
			<th>Opcoes</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach($this->usuarios as $usuario): ?>
		<tr>
			<td><a href="<?php echo $this->baseUrl();?>/usuarios/index/view/id/<?php echo $usuario['_id'];?>"><?php echo $usuario['nome'];?></a></td>
			<td><?php echo $usuario['email'];?></td>
			<td>
				<a class="btn btn-primary" href="<?php echo $this->baseUrl();?>/index.php/usuarios/index/update/id/<?php echo $usuario['_id'];?>">Editar</a>
				<button target="#myModal" id="excluir" value="<?php echo $usuario['_id'];?>" role="button" class="btn btn-danger" data-toggle="modal">Remover</button>
			</td>
		</tr>
	<?php endforeach; ?>
	</tbody>
</table>
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
		<h3 id="myModalLabel">Excluir Cadastro</h3>
	</div>
	<div class="modal-body">
		<p>Tem certeza que desejar excluir esse usuario?</p>
	</div>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
		<button id="confirma" class="btn btn-danger">OK</button>
	</div>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/js/bootstrap-modal.js"></script>
<script type="text/javascript">
			var id = 0;
			$("#excluir").click(function(){
				$('#myModal').modal();
				id = $("#excluir").attr("value");
			});
			
			$("#confirma").click(function(){
				jQuery.ajax({
					url: "/GeraAta/public/index.php/usuarios/index/delete/id/"+id,
					type: "POST",
					dataType: 'json',
					success: function(data){
						alert("Usuario removido com sucesso "+id);
					},
					error: function(){
						alert(id);
					}
				});
			});
		</script>