<h2>Usu&aacute;rios cadastrados</h2>
<a class="btn btn-success" href="<?php echo $this->baseUrl();?>/index.php/usuarios/index/add"><i class="icon-user"></i> Adicionar Usuario</a>
<table class="table talbe-stripped table-hover">
	<thead>
		<tr>
			<th>Nome</th>
			<th>Email</th>
			<th>Opcoes</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach($this->usuarios as $usuario): ?>
		<tr>
			<td><a href="<?php echo $this->baseUrl();?>/usuarios/index/view/id/<?php echo $usuario['_id'];?>"><?php echo $usuario['nome'];?></a></td>
			<td><?php echo $usuario['email'];?></td>
			<td>
				<a class="btn btn-primary" href="<?php echo $this->baseUrl();?>/index.php/usuarios/index/update/id/<?php echo $usuario['_id'];?>">Editar</a>
				<button target="#myModal" id="excluir" value="<?php echo $usuario['_id'];?>" role="button" class="btn btn-danger" data-toggle="modal">Remover</button>
			</td>
		</tr>
	<?php endforeach; ?>
	</tbody>
</table>
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<a type="button" class="close" data-dismiss="modal" aria-hidden="true">x</a>
		<h3 id="myModalLabel">Excluir Cadastro</h3>
	</div>
	<div class="modal-body">
		<p>Tem certeza que desejar excluir esse usuario?</p>
	</div>
	<div class="modal-footer">
		<a class="btn" data-dismiss="modal" aria-hidden="true">Fechar</a>
		<a id="confirma" class="btn btn-danger" data-dismiss="modal" aria-hidden="true">OK</a>
	</div>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/js/bootstrap-modal.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/js/removerUsuario.js"></script>