<h3>Formul&aacute;rio de Login</h3>
<hr>
<form action="" class="form-horizontal">
	<div class="control-group">
		<label class="label-control" for="username">Usuario</label>
		<div class="controls">
			<input type="text" id="username" name="username">
		</div>
	</div>
	<div class="control-group">
		<label class="label-control" for="password">Senha</label>
		<div class="controls">
			<input type="password" id="password" name="password">
		</div>
	</div>
	<div class="control-group">
		<div class="controls">
			<label class="checkbox">
				<input type="checkbox"> Remember me
			</label>
			<button type="submit" class="btn">Sign in</button>
		</div>
	</div>
</form>