<h3>Formul&aacute;rio de Login</h3>
<hr>
<form action="login" class="form-horizontal" method="post">
	<?php echo $this->erro; ?>
	<div class="control-group">
		<label class="control-label" for="username">Usu&aacute;rio</label>
		<div class="controls">
			<input type="text" id="username" name="username" placeholder="Usu&aacute;rio" required>
		</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="password">Senha</label>
		<div class="controls">
			<input type="password" id="password" name="password" placeholder="Senha" required>
		</div>
	</div>
	<div class="control-group">
		<div class="controls">
			<label class="checkbox">
				<input type="checkbox"> Lembrar Senha?
			</label>
			<button type="submit" class="btn btn-success btn-large">Entrar</button>
		</div>
	</div>
</form>
<script src="<?php echo $this->baseUrl(); ?>/public/js/bootstrap-alert.js"></script>