<!DOCTYPE html>
<html>
        <head>
                <title>Gera Ata</title>
                <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/bootstrap.css">
                <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/bootstrap-responsive.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/css/estilo.css ">
		<script src="http://code.jquery.com/jquery-latest.js"></script>
        </head>
        <body>
                <div class="container">
                        <?php echo $this->layout()->content; ?>
                </div>
        </body>
</html>
