<!DOCTYPE html>
<html>
     <head>
        <title>Gera Ata</title>
        <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/bootstrap.css">
        <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/bootstrap-responsive.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/estilo.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/themes/ui-lightness/jquery-ui.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/themes/ui-lightness/jquery.ui.datepicker.css">
		<script src="<?php echo $this->baseUrl(); ?>/public/js/jquery-1.8.3.js"></script>
     </head>
     <body>
        <div class="container">
        	<div class="navbar">
        		<div class="navbar-inner">
			    	<a class="brand" href="#">GeraAta</a>
			    	<ul class="nav">
			      		<li class="active"><a href="#">Home</a></li>
			      		<li><a href="<?php echo $this->baseUrl(); ?>/usuarios">Usu&aacute;rios</a></li>
			      		<li><a href="<?php echo $this->baseUrl(); ?>/atas">Atas</a></li>
			    	</ul>
			  	</div>
			</div>
        	<div class="row">
        		<div class="span12">
        			<?php echo $this->layout()->content; ?>
        		</div>
        	</div>
    	</div>
    	<hr>
    	<footer>
    		<div class="footer"><i class="icon-globe"></i> <a href="http://luizbrandao.com.br">Luiz Brand&atilde;o - Desenvolvimento Web</a></div>
    	</footer>
	</body>
</html>